services:
  app:
    image: ghcr.io/mooncellwiki/mw-devcontainer:latest

    volumes:
      - ../..:/workspaces
      - ./php/php.ini:/usr/local/etc/php/php.ini
    environment:
      - HTTP_RPXOY=http://172.22.240.1:7890
      - HTTPS_RPXOY=http://172.22.240.1:7890
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
  caddy:
    image: caddy:2.7
    volumes:
      - ../..:/workspaces
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    ports:
      - 81:80
  db:
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql

    # Add "forwardPorts": ["3306"] to **devcontainer.json** to forward MariaDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
  memcached:
    image: memcached:1.6
    restart: unless-stopped

  redis:
    image: redis:7.0
    restart: unless-stopped

volumes:
  mysql-data:
  caddy_data:
