name: deploy

on:
  push:
    branches:
      - MC1_39

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup PHP with composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: Install dependencies
        run: composer update --no-dev

      - name: Pack
        run: |
          cd ..
          tar --exclude-from=./mw/.github/workflows/exclude  -czvf dist.tgz mw
      - name: Get current time
        id: date
        run: echo "now=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GIHTUB_OUTPUT
      - name: Create release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: dist.tgz
          tag_name: ${{ steps.date.outputs.now }}
